[keyboard]
name = "RMK Sweep"
product_name = "RMK Sweep"
vendor_id = 0xc2ab
product_id = 0x3939
manufacturer = "tnargy"
chip = "rp2040"

[layout]
rows = 4
cols = 10
layers = 4
keymap = [
    [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", ],
        ["MT(A, LShift)", "MT(S, LAlt)", "MT(D, LCtrl)", "MT(F, LGui)", "G", "H", "MT(J, RGui)", "MT(K, RCtrl)", "MT(L, RAlt)", "MT(Semicolon, LShift)", ],
        ["Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", ],
        ["_", "_", "_", "LT(2, Tab)", "Enter", "Space", "LT(1, Backspace)", "_", "_", "_", ],
    ],
        ["Insert", "Kc1", "Kc2", "Kc3", "_", "Home", "PageDown", "PageUp", "End", "Colon", ],
        ["Delete", "_", "Kc4", "Kc5", "Kc6", "Left", "Down", "Up", "Right", "Semicolon", ],
        ["CapsLock", "_", "Kc7", "Kc8", "Kc9", "Kc0", "_", "_", "_", "_", ],
        ["_", "_", "_", "_", "Escape", "_", "_", "_", "_", "_", ],
    ],
    [
        ["_", "LeftBracket", LBRC, RBRC, "_", CARET, LPAR, RPAR, RBKT, TILDE, ],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", ],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", ],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", ],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", ],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", ],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", ],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", ],
    ],
]

[storage]

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms"}

[behavior.combo]
timeout = "150ms"
combos = [
  # Press J and K keys simultaneously to output Escape key
  { actions = ["J", "K"], output = "Escape" },
]


[split]
connection = "serial"

# we are defining the left side to be our primary.
[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_1" }]
[split.central.matrix]
matrix_type = "direct_pin"
direct_pins=[
    ["PIN_7", "PIN_26", "PIN_27", "PIN_28", "PIN_29", ],
    ["PIN_22", "PIN_20", "PIN_23", "PIN_21", "PIN_0", ],
    ["PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", ],
    ["_", "_", "_", "PIN_8", "PIN_9", ],
]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_1" }]
[split.peripheral.matrix]
matrix_type = "direct_pin"
direct_pins=[
    ["PIN_29", "PIN_28", "PIN_27", "PIN_26", "PIN_7", ],
    ["PIN_0", "PIN_21", "PIN_23", "PIN_20", "PIN_22", ],
    ["PIN_6", "PIN_5", "PIN_4", "PIN_3", "PIN_2", ],
    ["PIN_9", "PIN_8", "_", "_", "_", ],
]
